#!/bin/bash

W_INSTALL_TYPE="$wizard_install_type"
GITHUB="$wizard_github_path"

error() {
    echo "$@" > $TRIM_TEMP_LOGFILE
    exit 1
}

if [ "$W_INSTALL_TYPE" == "online" ]; then
    platform=$(uname -ms)

    command -v unzip >/dev/null ||
        error '需要安装 unzip 工具'

    case $platform in
    'Darwin x86_64')
        target=darwin-x64
        ;;
    'Darwin arm64')
        target=darwin-aarch64
        ;;
    'Linux aarch64' | 'Linux arm64')
        target=linux-aarch64
        ;;
    'MINGW64'*)
        error '不支持 Windows 系统'
        ;;
    'Linux riscv64')
        error '不支持 riscv64 架构'
        ;;
    'Linux x86_64' | *)
        target=linux-x64
        ;;
    esac

    case "$target" in
    'linux'*)
        if [ -f /etc/alpine-release ]; then
            target="$target-musl"
        fi
        ;;
    esac

    github_repo="$GITHUB/oven-sh/bun"

    # 如果 AVX2 不支持，则使用 -baseline 构建
    case "$target" in
    'darwin-x64'*)
        if [[ $(sysctl -a | grep machdep.cpu | grep AVX2) == '' ]]; then
            target="$target-baseline"
        fi
        ;;
    'linux-x64'*)
        if [[ $(cat /proc/cpuinfo | grep avx2) = '' ]]; then
            target="$target-baseline"
        fi
        ;;
    esac

    exe_name=bun
    tmp_dir=/tmp/bun-tmp-package
    zip_file=$tmp_dir/$exe_name.zip

    if [[ ! -d $tmp_dir ]]; then
        mkdir -p "$tmp_dir" ||
            error "无法创建临时目录 \"$tmp_dir\""
    fi

    # 如果 Bun.zip 存在就跳过下载
    if [[ ! -f "$zip_file" ]]; then
        bun_uri=$github_repo/releases/latest/download/bun-$target.zip
    
        curl --fail --location --output "$zip_file" "$bun_uri" ||
            error "无法从 \"$bun_uri\" 下载 Bun"
    fi
fi

exit 0